= JBoss Tools Playground

This github repository contains playful experiments in trying to make Eclipse better.

The intent is not to have a perfect, always updatable feature set but to try and explore
ideas and implementations while make it easy for everyone to try it out.

== Installation

Install from the following p2 repository http://download.jboss.org/jbosstools/builds/staging/jbosstools-playground_master/all/repo/ .
If you don't know how to do that, please read following documentation http://help.eclipse.org/luna/index.jsp?topic=/org.eclipse.platform.doc.user/tasks/tasks-127.htm .

== Contents

=== Easymport: Easy and smart Open/Import of a project

[NOTE]
This is progressively moving to the related Eclipse projects. Please see https://wiki.eclipse.org/E4/UI/Smart_Import

Aren't you sick of this messy "Import" wizard you see in Eclipse? Can't
the IDE figure out what kind of project you're importing by itself? Yes,
it does. This plugins include a new _File > Open Project/Folder_ menu
which will just ask you for a directory and will do its best to figure
out what kind of project it is and run the most relevant import tricks.
It also supports ability to use the same Import mechanics, but simply by
_Drag and dropping_ a folder in the Project Explorer (in a working set
or on the workspace root).

Currently supported projects for easy import are: 

Eclipse projects:: directories that are already Eclipse projects will be imported "as it"
and will reuse existing configuration
Java projects:: will setup nature, detect and configure source folders 
JavaScript projects:: will setup nature, detect source and configure source folders 
Maven projects:: will import project as Maven project, and delegate its configuration to m2e according to the content of the pom.xml file 
Java EE Projects:: will enable the WebTools nature, and 
 * Web projects will enable Servlet facet 
 * JPA projects will enable JPA facet 
 * Jax-RS projects will enable Jax-rs facet 
PDE projects: 
 * Plugin project: will enable Plug-in Nature 
 * Feature project: will enable Feature Nature
Plain folders:: will be imported as new Eclipse projects, without additional configuration

This contains an extension point (link:plugins/org.jboss.tools.playground.easymport/src/org/jboss/tools/playground/easymport/extension/ProjectConfigurator.java[ProjectConfigurator.java]), so if you want to add support for
other types of projects, it's just a matter of adding an extension and
implementing a class.

Of course, this may not always give you the perfect result. It is
recommended after such an import to have a look at your project
properties and see whether there are some things that need more specific
configuration.

Reference Eclipse bug: http://bugs.eclipse.org/421930

=== Naturist: Edit project natures

There are cases where you really want to hack your project, and are
ready to take all the risks that go with it. So these plugins add a
Project Property page that allow to add or remove project natures.
Beware that this is a risky operation, so do it only when you're sure of
what you're doing. Usually, enabling a nature is only 1 step in the
configuration, so after you enabled a new nature, you'll most likely
want to open (again) the Project Settings page and tweak the new pages
as desired.

Reference Eclipse bug: https://bugs.eclipse.org/102527

=== Auto-update out-of-date Maven project configuration

[NOTE]
This has been integrated in m2e 1.6, and will be integrated in Eclipse IDE starting
from Mars M6.

Tired of seeing these "Project configuration is out-of-date" errors whenever 
you tweak your pom.xml? This plugin will automatically do the 
`Maven` > `Update project configuration` for you. *Currently* the only way to 
disable the plugin is to uncheck it under from `Preferences` > `Startup and Shutdown`
and restart the workspace. 

Reference Eclipse bug: https://bugs.eclipse.org/335720

=== Nestor: View Nested Projects

[NOTE]
With Eclipse ticket https://bugs.eclipse.org/427768 , Nestor has been migrated
to Eclipse Platform UI, and Nested view of projects in _Project Explorer_ will
be available by default in Eclipse 4.5 (Mars) M5 and later: https://www.eclipse.org/eclipse/news/4.5/M5/#nested-projects
